/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyIPPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  autoCopyOnInsert: false
};

// src/constants.ts
var API = {
  MYIP_URL: "https://api.myip.com"
};
var UI = {
  CMD_INSERT_IP_NAME: "Insert IP Info at Cursor",
  CMD_COPY_IP_NAME: "Copy Public IP to Clipboard",
  NOTICE_IP_INSERTED: "IP info inserted.",
  NOTICE_IP_COPIED: "IP address copied to clipboard.",
  NOTICE_NO_MD_EDITOR: "No active Markdown editor found.",
  NOTICE_HTTP_ERROR: (status) => `IP service returned an error (HTTP ${status}).`,
  NOTICE_PARSE_ERROR: "Failed to parse IP service response.",
  NOTICE_INCOMPLETE_DATA: "IP service returned incomplete data.",
  NOTICE_NETWORK_ERROR: "Network error: Unable to reach IP service. Check your internet connection.",
  NOTICE_UNEXPECTED_ERROR: "An unexpected error occurred while fetching IP info.",
  NOTICE_FETCH_ERROR: (msg) => `Failed to fetch IP info: ${msg}`,
  LABEL_IP: "IP Address:",
  LABEL_COUNTRY: "Country:",
  SETTING_AUTO_COPY_NAME: "Auto-copy IP on insert",
  SETTING_AUTO_COPY_DESC: "Automatically copy the IP address to clipboard when inserting into a note."
};

// main.ts
var MyIPPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MyIPSettingTab(this.app, this));
    this.registerCommands();
  }
  registerCommands() {
    this.addCommand({
      id: "insert-ip-info-inline",
      name: UI.CMD_INSERT_IP_NAME,
      callback: async () => {
        if (!this.ensureSettingsValid()) return;
        const data = await this.fetchIPInfo();
        if (!data) return;
        const html = `
<div class="ip-info-box">
  <div><strong>${UI.LABEL_IP}</strong> ${data.ip}</div>
  <div><strong>${UI.LABEL_COUNTRY}</strong> ${data.country} (${data.cc})</div>
</div>
          `.trim();
        const mdView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (mdView && mdView.editor) {
          mdView.editor.replaceSelection(html);
          new import_obsidian.Notice(UI.NOTICE_IP_INSERTED);
          if (this.settings.autoCopyOnInsert) {
            await navigator.clipboard.writeText(data.ip);
          }
        } else {
          new import_obsidian.Notice(UI.NOTICE_NO_MD_EDITOR);
        }
      }
    });
    this.addCommand({
      id: "copy-ip-to-clipboard",
      name: UI.CMD_COPY_IP_NAME,
      callback: async () => {
        if (!this.ensureSettingsValid()) return;
        const data = await this.fetchIPInfo();
        if (!data) return;
        await navigator.clipboard.writeText(data.ip);
        new import_obsidian.Notice(UI.NOTICE_IP_COPIED);
      }
    });
  }
  /**
   * Ensures required settings are present before executing logic.
   */
  ensureSettingsValid() {
    if (!this.settings) {
      new import_obsidian.Notice("Plugin settings not loaded correctly.");
      return false;
    }
    return true;
  }
  async fetchIPInfo() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: API.MYIP_URL,
        method: "GET",
        throw: false
      });
      if (response.status < 200 || response.status >= 300) {
        new import_obsidian.Notice(UI.NOTICE_HTTP_ERROR(response.status));
        console.error("HTTP error:", response.status, response.text);
        return null;
      }
      let data;
      try {
        data = JSON.parse(response.text);
      } catch (parseError) {
        new import_obsidian.Notice(UI.NOTICE_PARSE_ERROR);
        console.error("JSON parse error:", parseError);
        return null;
      }
      if (!data.ip || !data.country || !data.cc) {
        new import_obsidian.Notice(UI.NOTICE_INCOMPLETE_DATA);
        console.error("Incomplete response:", data);
        return null;
      }
      return data;
    } catch (err) {
      console.error("Failed to fetch IP info:", err);
      if (err instanceof Error) {
        if (err.message.includes("net::ERR") || err.message.includes("Failed to fetch")) {
          new import_obsidian.Notice(UI.NOTICE_NETWORK_ERROR);
        } else {
          new import_obsidian.Notice(UI.NOTICE_FETCH_ERROR(err.message));
        }
      } else {
        new import_obsidian.Notice(UI.NOTICE_UNEXPECTED_ERROR);
      }
      return null;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var MyIPSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(UI.SETTING_AUTO_COPY_NAME).setDesc(UI.SETTING_AUTO_COPY_DESC).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoCopyOnInsert).onChange(async (value) => {
        this.plugin.settings.autoCopyOnInsert = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
